apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: scaletestapp-pod-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: scaletestapp
  podMetricsEndpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics