apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-monitor
  namespace: default
  labels:
    app: scaletestapp
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics